# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432​


development:
  <<: *default
  database: terrain_map_development

production:
  <<: *default
  database: dbjqbilcdt6tml
  user: aivqrfddvonpwm
  username: alter_messages
  password: <%= ENV['CRYPTO_MESSAGES_DATABASE_PASSWORD'] %>
  host: ec2-54-163-240-54.compute-1.amazonaws.com

